CREATE TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` (
	`HCP_PRODUCT_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_INFO 행 고유키',
	`CUSTOMER_NAME`	VARCHAR(90)	NOT NULL	COMMENT '예약자 이름',
	`CUSTOMER_PHONE_NUMBER`	VARCHAR(45)	NOT NULL	COMMENT '예약자 전화번호(국가번호 + 전화번호)',
	`RENTAL_START_DATETIME`	DATETIME	NOT NULL	COMMENT '대여가 시작되는 일시',
	`RENTAL_END_DATETIME`	DATETIME	NOT NULL	COMMENT '대여가 끝나는 일시 (회수 시간은 포함되지 않는 순수 서비스 이용 시간)',
	`PAYMENT_DEADLINE_DATETIME`	DATETIME	NOT NULL	COMMENT '예약 결재 기한 (예약 요청일로부터 생성, 이 시점이 지났고, payment_complete_datetime 가 충족되지 않았다면 취소로 간주)',
	`CANCELABLE_DEADLINE_DATETIME`	DATETIME	NOT NULL	COMMENT '예약 요청일로부터 생성, 예약 취소 신청 가능 기한',
	`RESERVATION_APPROVAL_DEADLINE_DATETIME`	DATETIME	NOT NULL	COMMENT '관리자 승인 기한 (이 시점이 지났고, reservation_approval_datetime 가 충족되지 않았다면 취소로 간주)',
	`PRODUCT_NAME`	VARCHAR(90)	NOT NULL	COMMENT '고객에게 보일 상품명(아래 부터는 예약 당시의 정보로, 영수증의 기능을 위한 정보 복제 컬럼)',
	`PRODUCT_INTRO`	VARCHAR(6000)	NOT NULL	COMMENT '고객에게 보일 상품 소개',
	`FRONT_IMAGE_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_IMAGE 행 고유키',
	`ADDRESS_COUNTRY`	VARCHAR(60)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가',
	`ADDRESS_MAIN`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가와 상세 주소를 제외',
	`ADDRESS_DETAIL`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 상세',
	`PREPARATION_MINUTE`	BIGINT UNSIGNED	NOT NULL	COMMENT '대여 상품 반납일시로부터 다음 대여까지 걸리는 시간'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_INFO` (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_CATEGORY 행 고유키',
	`PRODUCT_DESC`	VARCHAR(3000)	NOT NULL	COMMENT '대여 가능 상품 개별 설명',
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_IMAGE 행 고유키',
	`FIRST_RENTABLE_DATETIME`	DATETIME	NOT NULL	COMMENT '제품 대여(손님에게 제공)가 가능한 최초 일시',
	`STORAGE_DATETIME`	DATETIME	NULL	COMMENT '제품을 최종 회수하는 일시',
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_INFO 행 고유키',
	`NOW_RESERVABLE`	BIT(1)	NOT NULL	COMMENT '재고, 상품 상태와 상관 없이 현 시점 예약 가능한지에 대한 관리자의 설정'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_INFO` (
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_CATEGORY 행 고유키',
	`FRONT_IMAGE_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_IMAGE 행 고유키',
	`PRODUCT_NAME`	VARCHAR(90)	NOT NULL	COMMENT '고객에게 보일 상품명',
	`PRODUCT_INTRO`	VARCHAR(6000)	NOT NULL	COMMENT '고객에게 보일 상품 소개',
	`ADDRESS_COUNTRY`	VARCHAR(60)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가',
	`ADDRESS_MAIN`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가와 상세 주소를 제외',
	`ADDRESS_DETAIL`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 상세',
	`FIRST_RESERVABLE_DATETIME`	DATETIME	NOT NULL	COMMENT '상품 예약이 가능한 최초 일시(콘서트 티켓 예매와 같은 서비스를 가정, 예약 러시 처리가 필요)',
	`RESERVATION_UNIT_MINUTE`	BIGINT UNSIGNED	NOT NULL	COMMENT '예약 추가 할 수 있는 최소 시간 단위 (분)',
	`MINIMUM_RESERVATION_UNIT_COUNT`	INT UNSIGNED	NOT NULL	COMMENT '단위 예약 시간을 대여일 기준에서 최소 몇번 추가 해야 하는지',
	`MAXIMUM_RESERVATION_UNIT_COUNT`	INT UNSIGNED	NULL	COMMENT '단위 예약 시간을 대여일 기준에서 최대 몇번 추가 가능한지 (Null 이라면 제한 없음)',
	`RESERVATION_UNIT_PRICE`	BIGINT UNSIGNED	NOT NULL	COMMENT '단위 예약 시간에 대한 가격 (예약 시간 / 단위 예약 시간 * 예약 단가 = 예약 최종가)',
	`PREPARATION_MINUTE`	BIGINT UNSIGNED	NOT NULL	COMMENT '대여 상품 반납일시로부터 다음 대여까지 걸리는 시간',
	`NOW_RESERVABLE`	BIT(1)	NOT NULL	COMMENT '재고, 상품 상태와 상관 없이 현 시점 예약 가능한지에 대한 관리자의 설정'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_INFO` (
	`HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_PRODUCT_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_RESERVATION_INFO 행 고유키',
	`STATE_CODE`	TINYINT UNSIGNED	NOT NULL	COMMENT '예약 상태 코드(1 : 예약 신청, 2 : 결재 완료, 3 : 예약 승인, 4 : 예약 거부, 5 : 예약 취소 신청, 6 : 예약 취소 승인, 7 : 예약 취소 거부, 8 : 예약 취소 후 환불 완료, 9: 조기반납신청, 10:조기반납 확인)',
	`STATE_CHANGE_DESC`	VARCHAR(600)	NOT NULL	COMMENT '상태 변경 상세'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` (
	`HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_INFO 행 고유키',
	`HCP_PRODUCT_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_RESERVATION_INFO 행 고유키'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`CATEGORY_NAME`	VARCHAR(90)	NOT NULL	COMMENT '카테고리 이름',
	`PARENT_CATETORY_UID`	BIGINT UNSIGNED	NULL	COMMENT '부모 카테고리 고유키'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_IMAGE` (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_INFO 행 고유키',
	`IMAGE_FULL_URL`	VARCHAR(200)	NOT NULL	COMMENT '상품 이미지 Full URL'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`CATEGORY_NAME`	VARCHAR(90)	NOT NULL	COMMENT '카테고리 이름',
	`PARENT_CATEGORY`	BIGINT UNSIGNED	NOT NULL	COMMENT '부모 카테고리의 고유키'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_IMAGE` (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_INFO 행 고유키',
	`IMAGE_FULL_URL`	VARCHAR(200)	NOT NULL	COMMENT '상품 이미지 Full URL'
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_RESERVATION_INFO` PRIMARY KEY (
	`HCP_PRODUCT_RESERVATION_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_INFO` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_INFO` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_INFO` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_CATEGORY` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_CATEGORY` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_IMAGE` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_IMAGE` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_IMAGE` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_IMAGE` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_INFO_TO_HCP_RENTABLE_PRODUCT_RESERVATION_INFO_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_INFO` (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_IMAGE_TO_HCP_RENTABLE_PRODUCT_RESERVATION_INFO_1` FOREIGN KEY (
	`FRONT_IMAGE_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_IMAGE` (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_STOCK_CATEGORY_TO_HCP_RENTABLE_PRODUCT_STOCK_INFO_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_STOCK_IMAGE_TO_HCP_RENTABLE_PRODUCT_STOCK_INFO_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_STOCK_IMAGE` (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_INFO_TO_HCP_RENTABLE_PRODUCT_STOCK_INFO_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_INFO` (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_CATEGORY_TO_HCP_RENTABLE_PRODUCT_INFO_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_IMAGE_TO_HCP_RENTABLE_PRODUCT_INFO_1` FOREIGN KEY (
	`FRONT_IMAGE_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_IMAGE` (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_RESERVATION_INFO_TO_HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_INFO_1` FOREIGN KEY (
	`HCP_PRODUCT_RESERVATION_INFO_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` (
	`HCP_PRODUCT_RESERVATION_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_STOCK_INFO_TO_HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_STOCK_INFO` (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_RESERVATION_INFO_TO_HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO_1` FOREIGN KEY (
	`HCP_PRODUCT_RESERVATION_INFO_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` (
	`HCP_PRODUCT_RESERVATION_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_CATEGORY` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_CATEGORY_TO_HCP_RENTABLE_PRODUCT_CATEGORY_1` FOREIGN KEY (
	`PARENT_CATETORY_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_IMAGE` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_INFO_TO_HCP_RENTABLE_PRODUCT_IMAGE_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_INFO` (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_STOCK_CATEGORY_TO_HCP_RENTABLE_PRODUCT_STOCK_CATEGORY_1` FOREIGN KEY (
	`PARENT_CATEGORY`
)
REFERENCES `HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_IMAGE` ADD CONSTRAINT `FK_HCP_RENTABLE_PRODUCT_STOCK_INFO_TO_HCP_RENTABLE_PRODUCT_STOCK_IMAGE_1` FOREIGN KEY (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`
)
REFERENCES `HCP_RENTABLE_PRODUCT_STOCK_INFO` (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`
);

