CREATE TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` (
	`HCP_PRODUCT_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_INFO 행 고유키',
	`CUSTOMER_NAME`	VARCHAR(90)	NOT NULL	COMMENT '예약자 이름',
	`CUSTOMER_PHONE_NUMBER`	VARCHAR(45)	NOT NULL	COMMENT '예약자 전화번호(국가번호 + 전화번호)',
	`RENTAL_START_DATETIME`	DATETIME	NOT NULL	COMMENT '대여가 시작되는 일시',
	`RENTAL_END_DATETIME`	DATETIME	NOT NULL	COMMENT '대여가 끝나는 일시 (회수 시간은 포함되지 않는 순수 서비스 이용 시간)',
	`PAYMENT_CHECK_DEADLINE_DATETIME`	DATETIME	NOT NULL	COMMENT '예약 결재 확인 기한 (결재 기한 초과 처리.)',
	`RESERVATION_APPROVAL_DEADLINE_DATETIME`	DATETIME	NOT NULL	COMMENT '관리자 승인 기한 (이 시점이 지났고, reservation_approval_datetime 가 충족되지 않았다면 취소로 간주)',
	`PRODUCT_NAME`	VARCHAR(90)	NOT NULL	COMMENT '고객에게 보일 상품명(아래 부터는 예약 당시의 정보로, 영수증의 기능을 위한 정보 복제 컬럼)',
	`PRODUCT_INTRO`	VARCHAR(6000)	NOT NULL	COMMENT '고객에게 보일 상품 소개',
	`FRONT_IMAGE_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_IMAGE 행 고유키',
	`ADDRESS_COUNTRY`	VARCHAR(60)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가',
	`ADDRESS_MAIN`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가와 상세 주소를 제외',
	`ADDRESS_DETAIL`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 상세'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_INFO` (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_CATEGORY 행 고유키',
	`PRODUCT_DESC`	VARCHAR(3000)	NOT NULL	COMMENT '대여 가능 상품 개별 설명',
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_IMAGE 행 고유키',
	`FIRST_RENTABLE_DATETIME`	DATETIME	NOT NULL	COMMENT '제품 대여(손님에게 제공)가 가능한 최초 일시',
	`LAST_RENTABLE_DATETIME`	DATETIME	NULL	COMMENT '제품 대여 마지막 일시 (이때가 대여 마지막 날)',
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_INFO 행 고유키',
	`NOW_RESERVABLE`	BIT(1)	NOT NULL	COMMENT '재고, 상품 상태와 상관 없이 현 시점 예약 가능한지에 대한 관리자의 설정'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_INFO` (
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_CATEGORY 행 고유키',
	`FRONT_IMAGE_UID`	BIGINT UNSIGNED	NULL	COMMENT 'HCP_RENTABLE_PRODUCT_IMAGE 행 고유키',
	`PRODUCT_NAME`	VARCHAR(90)	NOT NULL	COMMENT '고객에게 보일 상품명',
	`PRODUCT_INTRO`	VARCHAR(6000)	NOT NULL	COMMENT '고객에게 보일 상품 소개',
	`ADDRESS_COUNTRY`	VARCHAR(60)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가',
	`ADDRESS_MAIN`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 국가와 상세 주소를 제외',
	`ADDRESS_DETAIL`	VARCHAR(300)	NOT NULL	COMMENT '상품이 위치한 주소(대여 가능 위치의 기준으로 사용됨) - 상세',
	`FIRST_RESERVABLE_DATETIME`	DATETIME	NOT NULL	COMMENT '상품 예약이 가능한 최초 일시(콘서트 티켓 예매와 같은 서비스를 가정, 예약 러시 처리가 필요)',
	`RESERVATION_UNIT_MINUTE`	BIGINT UNSIGNED	NOT NULL	COMMENT '예약 추가 할 수 있는 최소 시간 단위 (분)',
	`MINIMUM_RESERVATION_UNIT_COUNT`	INT UNSIGNED	NOT NULL	COMMENT '단위 예약 시간을 대여일 기준에서 최소 몇번 추가 해야 하는지',
	`MAXIMUM_RESERVATION_UNIT_COUNT`	INT UNSIGNED	NULL	COMMENT '단위 예약 시간을 대여일 기준에서 최대 몇번 추가 가능한지 (Null 이라면 제한 없음)',
	`RESERVATION_UNIT_PRICE`	DECIMAL(15, 2) UNSIGNED	NOT NULL	COMMENT '단위 예약 시간에 대한 가격 (예약 시간 / 단위 예약 시간 * 예약 단가 = 예약 최종가)',
	`RESERVATION_UNIT_PRICE_CURRENCY_CODE`	CHAR(3)	NOT NULL	COMMENT '단위 예약 시간에 대한 가격 통화 코드(IOS 4217, ex : KRW, USD, EUR...)',
	`NOW_RESERVABLE`	BIT(1)	NOT NULL	COMMENT '재고, 상품 상태와 상관 없이 현 시점 예약 가능한지에 대한 관리자의 설정',
	`UPDATE_VERSION_SEQ`	INT UNSIGNED	NOT NULL	COMMENT '업데이트 버전 시퀀스 (0에서 시작해서 정보 업데이트가 될 때마다 1 씩 올라갑니다. 예약 프로세스 진행중 버전 정보가 맞지 않으면 진행이 불가능하게 할 것.)'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_HISTORY` (
	`HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_HISTORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_PRODUCT_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_RESERVATION_INFO 행 고유키',
	`STATE_CODE`	TINYINT UNSIGNED	NOT NULL	COMMENT '예약 상태 코드(0 : 관리자 결제 확인, 1 : 관리자 예약 승인, 2 : 관리자 예약 거부, 3 : 사용자 예약 취소 신청, 4 : 관리자 예약 취소 승인, 5 : 예약 취소 거부, 6: 사용자 조기반납신고, 7: 관리자 조기반납 확인, 8: 결제 환불 처리)',
	`STATE_CHANGE_DESC`	VARCHAR(600)	NOT NULL	COMMENT '상태 변경 상세',
	`STATE_CHANGE_DATETIME`	DATETIME	NOT NULL	COMMENT '상태 변경 기준 일시(행 생성일과 다르게 사건의 발생 일시 기준)'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` (
	`HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_INFO 행 고유키',
	`HCP_PRODUCT_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_RESERVATION_INFO 행 고유키',
	`NEXT_READY_DATETIME`	DATETIME	NULL	COMMENT '다음 준비 예정일(예약 후 상품의 다음 고객의 대여까지 준비가 완료되는 일시, 이 값이 null 이라면 다음 예약이 불가)'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`CATEGORY_NAME`	VARCHAR(90)	NOT NULL	COMMENT '카테고리 이름',
	`PARENT_CATETORY_UID`	BIGINT UNSIGNED	NULL	COMMENT '부모 카테고리 고유키'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_IMAGE` (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_INFO 행 고유키',
	`IMAGE_FULL_URL`	VARCHAR(200)	NOT NULL	COMMENT '상품 이미지 Full URL'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`CATEGORY_NAME`	VARCHAR(90)	NOT NULL	COMMENT '카테고리 이름',
	`PARENT_CATEGORY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '부모 카테고리의 고유키'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_STOCK_IMAGE` (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_STOCK_INFO 행 고유키',
	`IMAGE_FULL_URL`	VARCHAR(200)	NOT NULL	COMMENT '상품 이미지 Full URL'
);

CREATE TABLE `HCP_PAYMENT` (
	`HCP_HCP_PAYMENT_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`PAYMENT_TYPE`	TINYINT UNSIGNED	NOT NULL	COMMENT '결제 타입(1 : 무통장 입금, 2 : 실시간 계좌이체, 3 : 토스 페이)',
	`PAYMENT_AMOUNT`	DECIMAL(15, 2) UNSIGNED	NOT NULL	COMMENT '결제 금액',
	`PAYMENT_CURRENCY_CODE`	CHAR(3)	NOT NULL	COMMENT '결제 금액 통화 코드(IOS 4217, ex : KRW, USD, EUR...)',
	`PAYMENT_COMPLETE_DATETIME`	DATETIME(3)	NULL	COMMENT '결제가 완료 및 확인 된 일시(Null 이라면 아직 완료 처리가 아님)',
	`PAYMENT_FAILED`	BIT(1)	NOT NULL	COMMENT '결제4 실패 여부'
);

CREATE TABLE `HCP_PAYMENT_REAL_TIME_TRANSFERS` (
	`HCP_PAYMENT_REAL_TIME_TRANSFERS_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_HCP_PAYMENT_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`BANK_NAME`	VARCHAR(100)	NOT NULL	COMMENT '입금 은행명',
	`ACCOUNT_NUMBER`	VARCHAR(50)	NOT NULL	COMMENT '입금 은행 계좌번호',
	`DEPOSITOR_NAME`	VARCHAR(100)	NOT NULL	COMMENT '입금자명'
);

CREATE TABLE `HCP_PAYMENT_VIRTUAL_ACCOUNT_PAY` (
	`HCP_PAYMENT_VIRTUAL_ACCOUNT_PAY_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_HCP_PAYMENT_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`BANK_NAME`	VARCHAR(100)	NOT NULL	COMMENT '입금 은행명',
	`VIRTUAL_ACCOUNT_NUMBER`	VARCHAR(50)	NOT NULL	COMMENT '입금 은행 계좌번호',
	`DEPOSITOR_NAME`	VARCHAR(100)	NOT NULL	COMMENT '입금자명'
);

CREATE TABLE `HCP_PAYMENT_TOSS_PAYMENT` (
	`HCP_PAYMENT_TOSS_PAYMENT_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_HCP_PAYMENT_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`TOSS_TRANSACTION_ID`	VARCHAR(255)	NOT NULL	COMMENT 'Toss 거래 아이디'
);

CREATE TABLE `HCP_PAYMENT_REFUND` (
	`HCP_PAYMENT_REFUND_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_HCP_PAYMENT_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_PAYMENT 행 고유키',
	`AMOUNT`	DECIMAL(15, 2) UNSIGNED	NOT NULL	COMMENT '환불 금액',
	`CURRENCY_CODE`	CHAR(3)	NULL	COMMENT '환불 금액 통화 코드(IOS 4217, ex : KRW, USD, EUR...)',
	`REFUND_DATETIME`	DATETIME(3)	NULL	COMMENT '환불 완료한 일시'
);

CREATE TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_PAYMENT_INFO` (
	`HCP_PAYMENT_REFUND_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT '행 고유키',
	`DEL_FRAG`	BIT(1)	NOT NULL	COMMENT '행 삭제여부',
	`ROW_CREATE_DATETIME`	DATETIME(3)	NOT NULL	COMMENT '행 생성일시',
	`HCP_PRODUCT_RESERVATION_INFO_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_RENTABLE_PRODUCT_RESERVATION_INFO 행 고유키',
	`HCP_HCP_PAYMENT_UID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'HCP_PAYMENT 행 고유키'
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_RESERVATION_INFO` PRIMARY KEY (
	`HCP_PRODUCT_RESERVATION_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_INFO` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_STOCK_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_INFO` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_HISTORY` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_HISTORY` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_RESERVATION_STATE_CHANGE_HISTORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_STOCK_RESERVATION_INFO_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_CATEGORY` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_CATEGORY` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_IMAGE` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_IMAGE` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_CATEGORY` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_CATEGORY_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_STOCK_IMAGE` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_STOCK_IMAGE` PRIMARY KEY (
	`HCP_RENTABLE_PRODUCT_IMAGE_UID`
);

ALTER TABLE `HCP_PAYMENT` ADD CONSTRAINT `PK_HCP_PAYMENT` PRIMARY KEY (
	`HCP_HCP_PAYMENT_UID`
);

ALTER TABLE `HCP_PAYMENT_REAL_TIME_TRANSFERS` ADD CONSTRAINT `PK_HCP_PAYMENT_REAL_TIME_TRANSFERS` PRIMARY KEY (
	`HCP_PAYMENT_REAL_TIME_TRANSFERS_UID`
);

ALTER TABLE `HCP_PAYMENT_VIRTUAL_ACCOUNT_PAY` ADD CONSTRAINT `PK_HCP_PAYMENT_VIRTUAL_ACCOUNT_PAY` PRIMARY KEY (
	`HCP_PAYMENT_VIRTUAL_ACCOUNT_PAY_UID`
);

ALTER TABLE `HCP_PAYMENT_TOSS_PAYMENT` ADD CONSTRAINT `PK_HCP_PAYMENT_TOSS_PAYMENT` PRIMARY KEY (
	`HCP_PAYMENT_TOSS_PAYMENT_UID`
);

ALTER TABLE `HCP_PAYMENT_REFUND` ADD CONSTRAINT `PK_HCP_PAYMENT_REFUND` PRIMARY KEY (
	`HCP_PAYMENT_REFUND_UID`
);

ALTER TABLE `HCP_RENTABLE_PRODUCT_RESERVATION_PAYMENT_INFO` ADD CONSTRAINT `PK_HCP_RENTABLE_PRODUCT_RESERVATION_PAYMENT_INFO` PRIMARY KEY (
	`HCP_PAYMENT_REFUND_UID`
);

