# (실행 환경 local 설정)
# : 로컬 환경 개발자를 위한 환경 설정 = 서버 개발자가 마음껏 사용 가능 (그냥 IDE 를 실행하면 적용)

spring:
  application:
    # Eureka 에 등록될 서비스 이름 (복제 서버는 같은 이름으로 설정하여 로드밸런싱)
    name: SPRING-ADMIN-CLIENT1-LOCAL

  config:
    activate: # 프로필명 설정
      on-profile: local

  servlet:
    multipart:
      # !!!multipart 데이터량 설정!!!
      maxFileSize: 50MB
      maxRequestSize: 50MB

  boot:
    admin:
      client:
        # Spring Admin 등록
        auto-registration: true
        # Spring Admin 서버 위치
        url: http://127.0.0.1:9090
        instance:
          # 내 서버 접속 주소
          service-url: http://127.0.0.1:9191
          # 내 서버 이름
          name: SPRING-ADMIN-CLIENT1-LOCAL
        # Spring Admin 인증/인가 정보
        username: admin
        password: qwer1234

logging:
  file:
    # Spring Admin 로그 모니터링 파일
    name: ./by_product_files/spring_admin_client1/logs/local_current_log.log

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  # cors 허용 리스트 설정 (설정하지 않으면 모든 요청 허용)
  cors-allow-list: http://localhost:8081, http://127.0.0.1:8081, http://localhost:3000, http://127.0.0.1:3000