# (실행 환경 dev 설정)
# : 개발 환경 개발자들을 위한 환경 설정

spring:
  application:
    # Eureka 에 등록될 서비스 이름 (복제 서버는 같은 이름으로 설정하여 로드밸런싱)
    name: SPRING-ADMIN-CLIENT2-DEV

  config:
    activate: # 프로필명 설정
      on-profile: dev

  boot:
    admin:
      client:
        # Spring Admin 등록
        auto-registration: true
        # Spring Admin 서버 위치
        url: http://127.0.0.1:9090
        instance:
          # 내 서버 접속 주소
          service-url: http://127.0.0.1:${server.port}
          # 내 서버 이름
          name: ${spring.application.name}
        # Spring Admin 인증/인가 정보
        username: admin
        password: qwer1234

logging:
  file:
    # Spring Admin 로그 모니터링 파일
    name: ./by_product_files/spring_admin_client2/logs/dev_current_log.log