# (실행 환경 공통 설정)
# : 개발 환경에 상관 없이 공통으로 적용되는 설정

spring:
  boot:
    admin:
      ui:
        poll-timer:
          logfile: 3000    # logfile 갱신 주기. 30초로 설정함

  profiles:
    group: # 프로필 그룹 생성 - 새로운 프로필명에, 하위 프로필들을 조합. 생성한 그룹은 spring.config.activate.on-profile 에서 명시해줘야함
      # !!!모듈별 설정 파일이 늘어나면 아래에 반영하기!!!
      local9090:
        - local
        - port9090
      dev9090:
        - dev
        - port9090
      prod80:
        - prod
        - port80
    default: local9090 # jar 실행시 프로필 설정이 없을 때 적용할 프로필
    # IDE 실행 프로필 설정은, 실행 - 구성편집에서 VM 옵션 안에 -Dspring.profiles.active=dev8080 이렇게 설정 가능
    # prod 실행 포트를 나눠둔 이유는 배포 서버의 무중단 배포시 스위칭을 위한 것