services:
  mysql1:
    container_name: mysql1
    image: mysql:latest
    restart: always
    ports:
      - 33061:3306
    environment:
      # 초기 생성 데이터베이스
      MYSQL_DATABASE: first_schema
      # root 계정 초기 비밀번호
      MYSQL_ROOT_PASSWORD: todo1234!
      # 타임존 설정
      TZ: Asia/Seoul
    volumes:
      - C:/Users/raill/Downloads/tmp/mysql_cluster/mysql1/var/lib/mysql:/var/lib/mysql
      - C:/Users/raill/Downloads/tmp/mysql_cluster/mysql1/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./conf/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  
  mysql2:
    container_name: mysql2
    image: mysql:latest
    restart: always
    ports:
      - 33062:3306
    environment:
      # 초기 생성 데이터베이스
      MYSQL_DATABASE: first_schema
      # root 계정 초기 비밀번호
      MYSQL_ROOT_PASSWORD: todo1234!
      # 타임존 설정
      TZ: Asia/Seoul
    volumes:
      - C:/Users/raill/Downloads/tmp/mysql_cluster/mysql2/var/lib/mysql:/var/lib/mysql
      - C:/Users/raill/Downloads/tmp/mysql_cluster/mysql2/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./conf/setup.sql:/docker-entrypoint-initdb.d/setup.sql